### ISSUE TITLE
14.04. Vertaisarvionti tsoha

### ISSUE THREAD

**Issue by VoxBorealis** [juhkarhu/tsoha-kuvaruutu#1]
- When I click on an image, I think it would be more convenient if it redirected me to the post's page
  rather than opening the picture. (If it's possible)
- Right now, if I want to see the comments on a post, I have to press the little "Comment" button, which is not so convenient.
- Images uploaded to the website are really large at the moment, I would experiment with setting a fixed size for them.

- The app's code is very readable and overall clean.
- I like your implementation of 3rd party libraries (WTForms, CSRFProtect...)

**Comment by juhkarhu** [comment]
Thanks for the review!

- Redirecting works now as you suggested, thanks for the idea! 
- Regarding seeing the comments, I plan to implement that the index-page shows the most recent comment (or top3 maybe). 
- Images too are now resized (such progress, much wow). 

Thanks for the other remarks as well :)
