### ISSUE TITLE
Code Review 2

### ISSUE THREAD

**Issue by prTopi** [juhkarhu/tsoha-kuvaruutu#2]
The website overrall looks good and feels well made. Using it was also really straightforward.
Hiding comments seems to be broken at the moment, I got an 500 internal error while trying to do it.
Also, really small thing, but there seems to be a small typo on register page: ConfirmPassword

Code also looks clean and database schema sensible.
There seems to a small amount of unused or debug code mixed in, most of it commented out except for example in users.py

Nothing else to comment on comes to mind, good work!

**Comment by juhkarhu** [comment]
Comment hiding and the typo is also fixed, along with the debug code being removed among other things.

Thanks for the comments, much appreciated!
